#!/bin/sh

on_exit()
{
#  mountpoint -q /proc && umount /proc
#  umount /proc
  exec /bin/init $*
}
trap on_exit 0

mount -t proc proc /proc
grep -q overlay /proc/filesystems || { echo "Overlay: Not supported by kernel"; exit; }

mount -t tmpfs inittemp /mnt
mkdir /mnt/lower
mkdir /mnt/rw
mount -t tmpfs root-rw /mnt/rw


mkdir /mnt/rw/upper
mkdir /mnt/rw/work
mkdir /mnt/newroot

rootDev=`awk '$2 == "/" {print $1}' /etc/fstab`
rootMountOpt=`awk '$2 == "/" {print $4}' /etc/fstab`
rootFsType=`awk '$2 == "/" {print $3}' /etc/fstab`
mount -t ${rootFsType} -o ${rootMountOpt},ro ${rootDev} /mnt/lower


mount -t overlay -o lowerdir=/mnt/lower,upperdir=/mnt/rw/upper,workdir=/mnt/rw/work overlayfs-root /mnt/newroot

mkdir /mnt/newroot/ro
mkdir /mnt/newroot/rw
# remove root mount from fstab (this is already a non-permanent modification)
grep -v "$rootDev" /mnt/lower/etc/fstab > /mnt/newroot/etc/fstab

cd /mnt/newroot
pivot_root . mnt





